<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * renvoie les articles pour la page d'accueil
     * @return array d'objet
     */
    public function getHomePageArticles($limit =null)
    {
        return $this->findBy(
                array('published' => true,'enabled' => true),
                array('publishDate' => 'desc'),$limit
                );
    }
 }
