<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
       private $limit = 2 ;
    /**
     * renvoie les articles pour la page d'accueil
     * @return array d'objet
     */
    public function getHomePageArticles($page = 0)
    {

        $offset = $this->limit *$page;
        return $this->findBy(
                array('published' => true,'enabled' => true),
                array('publishDate' => 'desc'),
                        $this->limit,$offset);
    }
    /**
     * Renvoi le nombre de page de la requête
     * @return int
     */
    public function getHomePageCountArticles()
    {
        $nbArticles =$this->createqueryBuilder("a")
                ->where("a.published = 1")
                ->andWhere("a.enabled = 1")
                ->select("count(a)")
                ->getQuery()
                ->getSingleScalarResult();
        return (int)ceil($nbArticles/$this->limit);
    }
}
